alias ls='ls --color=auto'
alias ll='ls -lah'
alias cat='batcat'
alias find='fdfind'
alias grep='rg'
alias vim='nvim'
alias dc='docker compose'
alias ..='cd ..'
alias open='explorer.exe .'
alias ...='cd ../..'
alias wsl-restart='wsl.exe --shutdown'
alias cdc='claude --dangerously-skip-permissions --continue'
alias cc='claude --continue'
alias p='pnpm run'
alias n='npm run'
alias skillpush='skillshare sync && cd ~/.config/skillshare && skillshare commit && git push && cd -'